### ISSUE TITLE
Bug: ibm-fncm-secret is incorrect

### ISSUE THREAD

**Issue by faraz** [ibm-client-engineering/solution-filenet-aws#10]
Investigating why CPE initialization fails, I noticed that in 
[fncm-secret creation phase](https://ibm-client-engineering.github.io/solution-filenet-aws/Create/solution-deploy#create-the-ibm-fncm-secret) the username is incorrect

```
kubectl create secret generic ibm-fncm-secret \
--from-literal=gcdDBUsername="ceuser" --from-literal=gcdDBPassword="p@ssw0rd" \
--from-literal=osDBUsername="ceuser" --from-literal=osDBPassword="p@ssw0rd" \
--from-literal=appLoginUsername="filenet_admin" --from-literal=appLoginPassword="p@ssw0rd" \
--from-literal=keystorePassword="p@ssw0rd" \
--from-literal=ltpaPassword="p@ssw0rd"
```

`--from-literal=appLoginUsername="filenet_admin"` needs to be `--from-literal=appLoginUsername="cpadmin" per the LDAP being set up here [HERE](https://ibm-client-engineering.github.io/solution-filenet-aws/Create/solution-deploy#create-configmaps-and-secrets)

Official https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/20.0.x?topic=pifcm-creating-secrets-protect-sensitive-filenet-content-manager-configuration-data#taskd48794e30 clearly states the user is the LDAP user

**Comment by cwalker-ibm** [comment]
Opened CR:

- Under 'shared_configuration' section made the following changes:
- Uncomment 'sc_deployment_hostname_suffix:' line and change the host name to "filenet.ics-cots-np.eksnp.aws.travp.net"
<img width="403" alt="Screenshot 2023-05-18 at 1 07 01 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/2ce9719c-d4fe-4a8e-a79d-e33f8669a432">

**Comment by cwalker-ibm** [comment]
Made the following changes to **'initialize_configuration'**:

Added the names for the following lines:
- ic_ldap_admins_groups_name
- ic_ldap_admin_user_name
- oc_cpe_obj_store_admin_user_group
<img width="855" alt="Screenshot 2023-05-18 at 1 08 01 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/cef7df53-7417-4943-a054-5125e8d0edeb">

- Added the section 'ic_domain_creation:' with the following information:
- domain_name: "P8DOMAIN"
- encryption_key: "128"

<img width="802" alt="Screenshot 2023-05-18 at 1 18 13 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/3e081783-23ca-4b6f-a7f2-454cb9632d58">

**Comment by cwalker-ibm** [comment]
Update all 'Resources' to 500m cpu:
<img width="464" alt="Screenshot 2023-05-18 at 1 19 12 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/5013fb1f-57f9-448d-854b-1567071541f2">

Applied the CR to the cluster:
<img width="838" alt="Screenshot 2023-05-18 at 1 13 27 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/ad4e8120-4ba3-4ca2-926b-eedf4cd9fbb5">

Scale Operator back UP (We scaled it down to set up ingress) and checked deployments and pods
<img width="990" alt="Screenshot 2023-05-18 at 1 25 41 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/31caf1c7-b219-4648-ab4c-025663403dbd">
<img width="832" alt="Screenshot 2023-05-18 at 1 26 14 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/4cde0e78-d98d-43a2-a1f4-f92b11364beb">

Exec into operator pod to view tasks completing but it would always error out, something was preventing bootstrap process.

Retrieved logs for further review
<img width="1325" alt="Screenshot 2023-05-18 at 2 11 49 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/3dd33e95-7f6c-439c-8dba-1af3db032260">
