### ISSUE TITLE
Ingress doesn’t come up correctly for the /acce url

### ISSUE THREAD

**Issue by Myron-Woods-IBM** [ibm-client-engineering/solution-filenet-aws#11]
**Description:**
The ingress for the /acce URL in FileNet 5.5.10 running on AWS EKS is not working correctly. When accessing the /acce URL and logging in, a blank screen is displayed. However, if the fncmdeploy-cpe-svc is port-forwarded, login is successful.

![Issue](https://github.com/ibm-client-engineering/solution-filenet-aws/assets/132930716/d7121756-0a06-46a8-a16b-f67fd4603b62)

**Steps to Reproduce:**
- Access the /acce URL.
- Log in and observe the blank screen.

**Expected Behavior:**
Logging in through the /acce URL should display the expected content.

**Ingress Description:**

    Name:             fncmdeploy-fncm-ingress
    Labels:           app=fncmdeploy-fncm-ingress
    Namespace:        filenet
    Address:          k8s-ingressn-ingressn-2a2a87bca6-cbe86a7bf0ba4eaa.elb.us-east-1.amazonaws.com
    Ingress Class:    <none>
    Default backend:  <default>
    TLS:
      fncmdeploy-fncm-ext-tls-secret terminates filenet.filenet-east.frwd-labs.link
    Rules:
      Host                                 Path  Backends
      ----                                 ----  --------
      filenet.filenet-east.frwd-labs.link  
                                           /acce                       fncmdeploy-cpe-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /ibm/wsatservice            fncmdeploy-cpe-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /P8CE                       fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /FileNet                    fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /wsi                        fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /peengine                   fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /pewsi                      fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /ibmccepo                   fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /restReg                    fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /clientDownload             fncmdeploy-cpe-stateless-svc:9443 (192.168.30.142:9443,192.168.80.197:9443)
                                           /content-services-graphql   fncmdeploy-graphql-svc:9443 (192.168.34.67:9443,192.168.95.110:9443)
                                           /openfncmis_wlp             fncmdeploy-cmis-svc:9443 (192.168.26.66:9443,192.168.33.49:9443)
                                           /taskManagerWeb             fncmdeploy-tm-svc:9443 (192.168.3.80:9443,192.168.51.120:9443)
                                           /contentapi                 fncmdeploy-es-svc:9443 (192.168.1.166:9443,192.168.86.4:9443)
                                           /sync                       fncmdeploy-navigator-svc:9443 (192.168.40.9:9443,192.168.65.66:9443)
                                           /navigator                  fncmdeploy-navigator-svc:9443 (192.168.40.9:9443,192.168.65.66:9443)
    Annotations:                           kubernetes.io/ingress.class: nginx
                                           nginx.ingress.kubernetes.io/affinity: cookie
                                           nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                                           nginx.ingress.kubernetes.io/force-ssl-redirect: true
                                           nginx.ingress.kubernetes.io/secure-backends: true
                                           nginx.ingress.kubernetes.io/session-cookie-hash: sha1
                                           nginx.ingress.kubernetes.io/session-cookie-name: route
                                           nginx.ingress.kubernetes.io/use-regex: true
    Events:
      Type    Reason  Age                From                      Message
      ----    ------  ----               ----                      -------
      Normal  Sync    18m (x6 over 46m)  nginx-ingress-controller  Scheduled for sync

**Comment by cwalker-ibm** [comment]
Had our first CPE Ingress diagnostic session with Larrel and Thuyanh
- Larrel checked web sphere trace logs
    - In console logs the error we were looking at 
        - 05/25/23 02:19:15:086 UTC] 00000357 SystemOut O CIWEB Info: [cpadmin@192.168.3.80] com.ibm.ecm.struts.actions.p8.P8LogonAction.createP8Connection() missing object store name
        - [05/25/23 02:19:15:347 UTC] 00000363 SystemOut O CIWEB Info: [@192.168.3.80] com.ibm.ecm.struts.actions.BaseActionHandlerImpl.executeAction() Invalid security token for: /plugin
        - [05/25/23 02:19:15:348 UTC] 00000363 SystemOut O CIWEB Error: [@192.168.3.80] com.ibm.ecm.mediator.BaseMediator.addError() add error: error.session.expired 1003
    - What was seen in messages log:
        - We can see connection being created and then the invalid security token error but there is not a lot of info on how it is throwing the missing object store name
        - com.ibm.ecm.struts.actions.p8.P8LogonAction.createP8Connection() missing object store name
        - [5/25/23 2:19:15:348 UTC] 00000363 SystemOut                                                   
        -  [05/25/23 02:19:15:347 UTC] 00000363 SystemOut O CIWEB Info: [@192.168.3.80] com.ibm.ecm.struts.actions.BaseActionHandlerImpl.executeAction() Invalid security token for: /plugin
        - [5/25/23 2:19:15:349 UTC] 00000363 SystemOut                                                   
        -  [05/25/23 02:19:15:348 UTC] 00000363 SystemOut O CIWEB Error: [@192.168.3.80] com.ibm.ecm.mediator.BaseMediator.addError() add error: error.session.expired 1003

Active Ingress annotations we are currently using:
Annotations:                 cert-manager.io/issuer: letsencrypt-prod
                                       kubernetes.io/ingress.class: nginx
                                       nginx.ingress.kubernetes.io/affinity: cookie
                                       nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                                       nginx.ingress.kubernetes.io/force-ssl-redirect: true
                                       nginx.ingress.kubernetes.io/secure-backends: true
                                       nginx.ingress.kubernetes.io/session-cookie-hash: sha1
                                       nginx.ingress.kubernetes.io/session-cookie-name: route

Noticed a principle unauthenticated error which seems like it is not picking up on the user account:
- 5/25/23 2:19:15:049 UTC] 00000357 HttpRequestMe 1   setRequestURL input [/acce/jaxrs/logon]
- [5/25/23 2:19:15:049 UTC] 00000326 HttpOutputStr <  getVc Exit  
                                 com.ibm.ws.channelfw.internal.InboundVirtualConnectionImpl@7359067c
- [5/25/23 2:19:15:049 UTC] 00000357 HttpRequestMe 3   setRequestURL: set URI to /acce/jaxrs/logon
- [5/25/23 2:19:15:049 UTC] 00000357 BNFHeadersImp 3   parseCRLFTokenExtract: start:23 lim:512 pos:23
- [5/25/23 2:19:15:049 UTC] 00000326 HttpOutputStr 3   setBufferSize=32768; HttpOutputStreamEE7@3c5520f1 writing=false closed=false bufferedCount=0 bytesWritten=0 error=null outindex=0
- [5/25/23 2:19:15:049 UTC] 00000357 BNFHeadersImp 3   length=17 pos=280, cachestart=262, start=262, trailingWhitespace=false
- [5/25/23 2:19:15:049 UTC] 00000326 WebSecurityCo <  getInvokedSubject Exit  
                                 Subject:
	Principal: WSPrincipal:UNAUTHENTICATED
	Public Credential: {com.ibm.wsspi.security.cred.uniqueId=user:o=defaultWIMFileBasedRealm/UNAUTHENTICATED, com.ibm.wsspi.security.cred.securityName=UNAUTHENTICATED}
	Public Credential: com.ibm.ws.security.credentials.wscred.WSCredentialImpl@3603c72b,realmName=o=defaultWIMFileBasedRealm,securityName=UNAUTHENTICATED,realmSecurityName=o=defaultWIMFileBasedRealm/UNAUTHENTICATED,uniqueSecurityName=UNAUTHENTICATED,primaryGroupId=null,accessId=null,groupIds=[]
	Private Credential: {com.ibm.wsspi.security.cred.uniqueId=user:o=defaultWIMFileBasedRealm/UNAUTHENTICATED, com.ibm.wsspi.security.cred.securityName=UNAUTHENTICATED}

**Comment by cwalker-ibm** [comment]
Checked HTTP status code when visiting ACCE
- Got 200 status code
- Picked up on host name correctly
- Logged in with CPE Admin and was still presented with blank page 
<img width="1190" alt="Screenshot 2023-05-25 at 3 32 54 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/8cfa6aad-81e9-42aa-9365-4cdbf0789dd9">

Checked the error messages we received:
<img width="1216" alt="Screenshot 2023-05-25 at 3 33 28 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/681e8231-fb0a-4b5a-8eeb-79325b37799c">

Thuyanh Nguyễn mentioned: Nginx returns a 404 error if it has no permission to read the requested file. If the files are stored in /etc/nginx/html/mywebsite , check that Nginx user (usually you name this user www-data or nginx ) has read permissions.


Checked Ingress logs for any potential errors related to unauthentication errors but did not see anything:
<img width="688" alt="Screenshot 2023-05-25 at 3 41 41 PM" src="https://github.com/ibm-client-engineering/solution-filenet-aws/assets/26884685/139456ac-d8da-4445-a438-3eaafedc396f">

**Comment by cwalker-ibm** [comment]
We are going to bring in Roger in a meeting tomorrow (5/26/23), he’s a software developer with a ton of experience with the backend auth methods for CPE.

Larrel is showing the logs to some of the liberty dev folks

**Comment by cwalker-ibm** [comment]
- They are using nginx for Ingress, when we login to acce we get a blank screen after login
- In the logs it is doing a logon connection then it immediately throws an error of a missing object store and then an invalid token error is thrown
    - [5/23/23 14:21:39:419 UTC] 00000028 SystemOut                                                    
    - O [05/23/23 14:21:39:419 UTC] 00000028 SystemOut O CIWEB Info: [cpadmin@192.168.52.52] com.ibm.ecm.util.NexusSessionListener.sessionDestroyed()  Session destroyed: [new: true, creationTime: 1684851699417, lastAccessedTime: 1684851699417, maxInactiveInterval: 1800] (153109478)
    - [5/23/23 14:21:39:442 UTC] 00000028 SystemOut                                                   
    -  O [05/23/23 14:21:39:441 UTC] 00000028 SystemOut O CIWEB Info: [cpadmin@192.168.52.52] com.ibm.ecm.struts.actions.p8.P8LogonAction.createP8Connection() missing object store name
    - [5/23/23 14:21:40:081 UTC] 00000059 SystemOut   
    - O [05/23/23 14:21:40:081 UTC] 00000059 SystemOut O CIWEB Info: [@192.168.52.52] com.ibm.ecm.struts.actions.BaseActionHandlerImpl.executeAction() Invalid security token for: /plugin
    - [5/23/23 14:21:40:082 UTC] 00000059 SystemOut   
- We can successfully get to login screen of navigator and port forwarding works if we port forward the actual service. It maps back to the pod and works.
- Team is not sure what the ingress could be doing in tandem with nginx
- Dev team thinks they might find more info when they run some debugging against the http end point 
- Our current LDAP configuration:
    - ldap_configuration:
    -   # Our example is actually using OpenLDAP, but this seems to be the only way to get it to work
    -     lc_selected_ldap_type: "IBM Security Directory Server"
    -     lc_ldap_precheck: true
    -   # Should be the cluster-ip of the ldap service
    -     lc_ldap_server: "10.100.217.46"
    -     lc_ldap_port: "389"
    -     lc_bind_secret: ldap-bind-secret
    -     lc_ldap_base_dn: "dc=filenet,dc=internal"
    -     lc_ldap_ssl_enabled: false
    -     lc_ldap_ssl_secret_name: "ldap"
    -     #lc_ldap_user_name_attribute: "*:uid"
    -     lc_ldap_user_name_attribute: "*:cn"
    -     lc_ldap_user_display_name_attr: "cn"
    -     lc_ldap_group_base_dn: "ou=Groups,dc=filenet,dc=internal"
    -     lc_ldap_group_name_attribute: "*:cn"
    -     lc_ldap_group_display_name_attr: "cn"
    -     lc_ldap_group_membership_search_filter: "(|(&(objectclass=groupofnames)(member={0}))(&(objectclass=groupofuniquenames)(uniquemember={0})))"
    -     lc_ldap_group_member_id_map: "groupofnames:member"
    -     tds:
        - lc_user_filter: "(&(cn=%v)(objectclass=inetOrgPerson))"


Narrowed issue down to being a networking and routing issue instead of an LDAP issue

**Comment by cwalker-ibm** [comment]
- They are using nginx for Ingress, when we login to acce we get a blank screen after login
- In the logs it is doing a logon connection then it immediately throws an error of a missing object store and then an invalid token error is thrown
    - [5/23/23 14:21:39:419 UTC] 00000028 SystemOut                                                    
    - O [05/23/23 14:21:39:419 UTC] 00000028 SystemOut O CIWEB Info: [cpadmin@192.168.52.52] com.ibm.ecm.util.NexusSessionListener.sessionDestroyed()  Session destroyed: [new: true, creationTime: 1684851699417, lastAccessedTime: 1684851699417, maxInactiveInterval: 1800] (153109478)
    - [5/23/23 14:21:39:442 UTC] 00000028 SystemOut                                                   
    -  O [05/23/23 14:21:39:441 UTC] 00000028 SystemOut O CIWEB Info: [cpadmin@192.168.52.52] com.ibm.ecm.struts.actions.p8.P8LogonAction.createP8Connection() missing object store name
    - [5/23/23 14:21:40:081 UTC] 00000059 SystemOut   
    - O [05/23/23 14:21:40:081 UTC] 00000059 SystemOut O CIWEB Info: [@192.168.52.52] com.ibm.ecm.struts.actions.BaseActionHandlerImpl.executeAction() Invalid security token for: /plugin
    - [5/23/23 14:21:40:082 UTC] 00000059 SystemOut   
- We can successfully get to login screen of navigator and port forwarding works if we port forward the actual service. It maps back to the pod and works.
- Team is not sure what the ingress could be doing in tandem with nginx
- Dev team thinks they might find more info when they run some debugging against the http end point 
- Our current LDAP configuration:
    - ldap_configuration:
    //Our example is actually using OpenLDAP, but this seems to be the only way to get it to work
    lc_selected_ldap_type: "IBM Security Directory Server"
    lc_ldap_precheck: true
    // Should be the cluster-ip of the ldap service
     lc_ldap_server: "10.100.217.46"
    lc_ldap_port: "389"
    lc_bind_secret: ldap-bind-secret
    lc_ldap_base_dn: "dc=filenet,dc=internal"
    lc_ldap_ssl_enabled: false
    lc_ldap_ssl_secret_name: "ldap"
    #lc_ldap_user_name_attribute: "*:uid"
    lc_ldap_user_name_attribute: "*:cn"
    lc_ldap_user_display_name_attr: "cn"
    lc_ldap_group_base_dn: "ou=Groups,dc=filenet,dc=internal"
    lc_ldap_group_name_attribute: "*:cn"
    lc_ldap_group_display_name_attr: "cn"
    lc_ldap_group_membership_search_filter: "(|(&(objectclass=groupofnames)(member={0}))(&(objectclass=groupofuniquenames)(uniquemember={0})))"
    -     lc_ldap_group_member_id_map: "groupofnames:member"
    -     tds:
        - lc_user_filter: "(&(cn=%v)(objectclass=inetOrgPerson))"


Narrowed issue down to being a networking and routing issue instead of an LDAP issue

**Comment by cwalker-ibm** [comment]
- They are using nginx for Ingress, when we login to acce we get a blank screen after login
- In the logs it is doing a logon connection then it immediately throws an error of a missing object store and then an invalid token error is thrown
     - [5/23/23 14:21:39:419 UTC] 00000028 SystemOut
     - [O [05/23/23 14:21:39:419 UTC] 00000028 SystemOut O CIWEB Info: [cpadmin@192.168.52.52] com.ibm.ecm.util.NexusSessionListener.sessionDestroyed() Session destroyed: [new: true, creationTime: 1684851699417, lastAccessedTime: 1684851699417, maxInactiveInterval: 1800] (153109478)
     - [[5/23/23 14:21:39:442 UTC] 00000028 SystemOut
     - [O [05/23/23 14:21:39:441 UTC] 00000028 SystemOut O CIWEB Info: [cpadmin@192.168.52.52] com.ibm.ecm.struts.actions.p8.P8LogonAction.createP8Connection() missing object store name
     - [[5/23/23 14:21:40:081 UTC] 00000059 SystemOut
     - [O [05/23/23 14:21:40:081 UTC] 00000059 SystemOut O CIWEB Info: [@192.168.52.52] com.ibm.ecm.struts.actions.BaseActionHandlerImpl.executeAction() Invalid security token for: /plugin
     - [[5/23/23 14:21:40:082 UTC] 00000059 SystemOut
- We can successfully get to login screen of navigator and port forwarding works if we port forward the actual service. It maps back to the pod and works.
- Team is not sure what the ingress could be doing in tandem with nginx
- Dev team thinks they might find more info when they run some debugging against the http end point
- Our current LDAP configuration:
ldap_configuration:
     //Our example is actually using OpenLDAP, but this seems to be the only way to get it to work
     lc_selected_ldap_type: "IBM Security Directory Server"
     lc_ldap_precheck: true
     // Should be the cluster-ip of the ldap service
     lc_ldap_server: "10.100.217.46"
     lc_ldap_port: "389"
     lc_bind_secret: ldap-bind-secret
     lc_ldap_base_dn: "dc=filenet,dc=internal"
     lc_ldap_ssl_enabled: false
     lc_ldap_ssl_secret_name: "ldap"
     #lc_ldap_user_name_attribute: ":uid"
     lc_ldap_user_name_attribute: ":cn"
     lc_ldap_user_display_name_attr: "cn"
     lc_ldap_group_base_dn: "ou=Groups,dc=filenet,dc=internal"
     lc_ldap_group_name_attribute: "*:cn"
     lc_ldap_group_display_name_attr: "cn"
     lc_ldap_group_membership_search_filter: "(|(&(objectclass=groupofnames)(member={0}))(&      (objectclass=groupofuniquenames)(uniquemember={0})))"
     lc_ldap_group_member_id_map: "groupofnames:member"
     tds:
          lc_user_filter: "(&(cn=%v)(objectclass=inetOrgPerson))"


Narrowed issue down to being a networking and routing issue instead of an LDAP issue

**Comment by dbridle** [comment]
Hi, we are also experiencing this exact same issue.  Our problem is showing the same error "missing object store".  We have the same lc_ldap config except active directory.  Ours appears to be an SSL issue where we are setting "-Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true", however, in acce when the deployment happens, the domain is not being created due to ldap issue.  Did you find out what the network and routing issue was?
